# Generated by Django 3.0.2 on 2020-04-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('filename', models.CharField(max_length=90)),
                ('filename_real', models.CharField(max_length=90)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
